#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Edoardo Baldi <edoardob90@gmail.com>
#
export DOTDIR="$HOME/.dotfiles"
export DOT_DIR=${DOTDIR}
export DOT_REPO="https://github.com/edoardob90/dotfiles.git"

# Source Prezto.
if [[ -s "${DOTDIR:-$HOME}/zprezto/init.zsh" ]]; then
  source "${DOTDIR:-$HOME}/zprezto/init.zsh"
fi

# All the rest ...

# Set the path where ZSH should look for additional completion function
fpath=(~/.dotfiles/zsh/completion ${HOME}/.dotfiles/dotfiles-manager $fpath)

# dotfiles manager
if [[ -f ${DOTDIR}/dotfiles-manager/dot.sh ]]; then
    source ${DOTDIR}/dotfiles-manager/dot.sh
else
    echo "WARNING: dotfiles manager 'dot.sh' not found! Did you clone the repo recursively?" >&2
fi

# PATH and other useful ENV variables
# if commented, look in ~/.zprofile if the variable is already exported
# Source the local file ${HOME}/.env.zsh, if present
[[ -f ${HOME}/.env.zsh ]] && source ${HOME}/.env.zsh

# Make sure lang environment variables are ok
#export LC_ALL=en_US.UTF-8

# Something that works and should be sourced only if on macOS
if [[ $(uname) == 'Darwin' ]]; then
# MEGA cmd
    if [[ -e "/Applications/MEGAcmd.app" ]]; then
        export PATH=/Applications/MEGAcmd.app/Contents/MacOS:${PATH}
    fi

# Brew: use non-prefixed GNU utils
#  All commands have been installed with the prefix 'g'.
#  If you really need to use these commands with their normal names, you
#  can add a "gnubin" directory to your PATH from your bashrc like:
    export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

#  Additionally, you can access their man pages with normal names if you add
#  the "gnuman" directory to your MANPATH from your bashrc as well:
    export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
fi

# Base16 shell colors
# https://github.com/chriskempson/base16-shell
BASE16_SHELL="$DOTDIR/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# Additional settings: aliases, abbreviations, environment
# Source the first alias/abbrev/env file found. Look up in the follwing order: ${HOME}, ${DOTDIR}/zsh

for file in aliases abbrevs env; do
  if [[ -f ${HOME}/."$file".zsh ]]; then
      source $HOME/."$file".zsh
  else
      source $DOTDIR/zsh/"$file".zsh
  fi
done
