#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Edoardo Baldi <edoardob90@gmail.com>
#
export DOTDIR="$HOME/.dotfiles"

# Source Prezto.
if [[ -s "${DOTDIR:-$HOME}/zprezto/init.zsh" ]]; then
  source "${DOTDIR:-$HOME}/zprezto/init.zsh"
fi

# All the rest ...

# Set the path where ZSH should look for additional completion function
fpath=(~/.dotfiles/zsh/completion $fpath)

# PATH and other useful ENV variables
# if commented, look in ~/.zprofile if the variable is already exported
# Source the local file ${HOME}/.env.zsh, if present
[[ -f ${HOME}/.env.zsh ]] && source ${HOME}/.env.zsh

# Make sure lang environment variables are ok
#export LC_ALL=en_US.UTF-8

# Something that works and should be sourced only if on macOS
if [[ $(uname) == 'Darwin' ]]; then
# MEGA cmd
    if [[ -e "/Applications/MEGAcmd.app" ]]; then
        export PATH=/Applications/MEGAcmd.app/Contents/MacOS:${PATH}
    fi

# Brew: use non-prefixed GNU utils
#  All commands have been installed with the prefix 'g'.
#  If you really need to use these commands with their normal names, you
#  can add a "gnubin" directory to your PATH from your bashrc like:
    export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

#  Additionally, you can access their man pages with normal names if you add
#  the "gnuman" directory to your MANPATH from your bashrc as well:
    export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
fi

# Base16 shell colors
# https://github.com/chriskempson/base16-shell
BASE16_SHELL="$DOTDIR/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# Aliases
# Source the first alias file found. Look up in the follwing order: ~/.aliases.zsh, ~/.dotfiles/zsh/aliases.zsh
if [[ -f ${HOME}/.aliases.zsh ]]; then
    source $HOME/.aliases.zsh
else
    source $DOTDIR/zsh/aliases.zsh
fi

# Command abbreviations
source $DOTDIR/zsh/abbrevs.zsh
